__author__ = 'mtacer'

PLS_input_gdb = [
    'm:\\USLandGrid\\Alabama\\Alabama.mdb',
    'm:\\USLandGrid\\Alaska\\Alaska.mdb',
    'm:\\USLandGrid\\Arizona\\Arizona.gdb',
    'm:\\USLandGrid\\Arkansas\\Arkansas.gdb',
    'm:\\USLandGrid\\California\\California.gdb',
    'm:\\USLandGrid\\Colorado\\Colorado.gdb',
    'm:\\USLandGrid\\Florida\\Florida.gdb',
    'm:\\USLandGrid\\Idaho\\Idaho.gdb',
    'm:\\USLandGrid\\Illinois\\Illinois.gdb',
    'm:\\USLandGrid\\Indiana\\Indiana.gdb',
    'm:\\USLandGrid\\Iowa\\Iowa.gdb',
    'm:\\USLandGrid\\Kansas\\Kansas.gdb',
    'm:\\USLandGrid\\Louisiana\\Louisiana.gdb',
    'm:\\USLandGrid\\Michigan\\Michigan.gdb',
    'm:\\USLandGrid\\Minnesota\\Minnesota\\Minnesota.gdb',
    'm:\\USLandGrid\\Mississippi\\Mississippi.gdb',
    'm:\\USLandGrid\\Missouri\\Missouri.gdb',
    'm:\\USLandGrid\\Montana\\Montana.gdb',
    'm:\\USLandGrid\\Nebraska\\Nebraska.gdb',
    'm:\\USLandGrid\\Nevada\\Nevada.gdb',
    'm:\\USLandGrid\\NewMexico\\NewMexico.gdb',
    'm:\\USLandGrid\\NorthDakota\\NorthDakota.gdb',
    'm:\\USLandGrid\\Ohio\\Ohio.gdb',
    'm:\\USLandGrid\\Oklahama\\Oklahama.gdb',
    'm:\\USLandGrid\\Oregon\\Oregon.gdb',
    'm:\\USLandGrid\\SouthDakota\\SouthDakota.gdb',
    'm:\\USLandGrid\\Utah\\Utah.gdb',
    'm:\\USLandGrid\\Washington\\Washington.gdb',
    'm:\\USLandGrid\\Wisconsin\\Wisconsin.gdb',
    'm:\\USLandGrid\\Wyoming\\Wyoming.gdb']